inherit: true

build:
    environment:
        php: '5.5.25'
    dependencies:
        override:
            - { command: 'composer install --no-interaction --prefer-source', idle_timeout: 600 }
    tests:
        override:
            - bin/phpspec run --format=dot

filter:
    paths: [app/code/community/*]

build_failure_conditions:
    - 'elements.rating(<= D).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'

tools:
    external_code_coverage: false
    php_code_coverage:      false
    php_code_sniffer:
        config: { standard: 'Ecg' }
    php_changetracking: false
    php_sim: true
    php_cs_fixer: false
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

checks:
    php:
        custom_coding_standard:
            git_repository: 'https://github.com/inviqa/magento-phpcs-coding-standard.git'
            git_version: 'origin/master'
            ruleset_path: 'ruleset.xml'